//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using System.Collections.Generic;
    using FTN;
    using FTN.Common;
    using FTN.Services.NetworkModelService.DataModel.Core;


    /// TimePoints for a schedule where the time between the points varies.
    public class IrregularTimePoint : IdentifiedObject {
        
        /// An IrregularTimePoint belongs to an IrregularIntervalSchedule.
        private long intervalSchedule=0;
        
        
        private long time;
        
        private float value1;
        
        private float value2;
        
        

        public IrregularTimePoint(long globalId) : base(globalId)
        {
        }

        public long IntervalSchedule { get => intervalSchedule; set => intervalSchedule = value; }
        public long Time { get => time; set => time = value; }
        public float Value1 { get => value1; set => value1 = value; }
        public float Value2 { get => value2; set => value2 = value; }

        public override bool Equals(object obj)
        {
            if (base.Equals(obj))
            {
                IrregularTimePoint x = (IrregularTimePoint)obj;
                return ((x.value1 == this.value1) &&
                    (x.value2 == this.value2) &&
                    (x.time == this.time) &&
                    (x.intervalSchedule == this.intervalSchedule));
            }
            else
            {
                return false;
            }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override bool HasProperty(ModelCode t)
        {
            switch (t)
            {
                case ModelCode.IRREGULARTPOINT_IREGULARISCHEDULE:
                case ModelCode.IRREGULARTPOINT_TIME:
                case ModelCode.IRREGULARTPOINT_VALUE1:
                case ModelCode.IRREGULARTPOINT_VALUE2:
                    return true;

                default:
                    return base.HasProperty(t);
            }
        }

        public override void GetProperty(Property prop)
        {
            switch (prop.Id)
            {
                case ModelCode.IRREGULARTPOINT_IREGULARISCHEDULE:
                    prop.SetValue(intervalSchedule);
                    break;
                case ModelCode.IRREGULARTPOINT_TIME:
                    prop.SetValue(time);
                    break;
                case ModelCode.IRREGULARTPOINT_VALUE1:
                    prop.SetValue(value1);
                    break;
                case ModelCode.IRREGULARTPOINT_VALUE2:
                    prop.SetValue(value2);
                    break;
                default:
                    base.GetProperty(prop);
                    break;
            }
        }

        public override void SetProperty(Property property)
        {
            switch (property.Id)
            {
                case ModelCode.IRREGULARTPOINT_IREGULARISCHEDULE:
                    intervalSchedule = property.AsReference();
                    break;
                case ModelCode.IRREGULARTPOINT_TIME:
                    time = property.AsInt();
                    break;
                case ModelCode.IRREGULARTPOINT_VALUE1:
                    value1 = property.AsFloat();
                    break;
                case ModelCode.IRREGULARTPOINT_VALUE2:
                    value1 = property.AsFloat();
                    break;

                default:
                    base.SetProperty(property);
                    break;
            }
        }

        public override void GetReferences(Dictionary<ModelCode, List<long>> references, TypeOfReference refType)
        {
            if (intervalSchedule != 0 && (refType == TypeOfReference.Reference || refType == TypeOfReference.Both))
            {
                references[ModelCode.IRREGULARTPOINT_IREGULARISCHEDULE] = new List<long>();
                references[ModelCode.IRREGULARTPOINT_IREGULARISCHEDULE].Add(intervalSchedule);
            }

            base.GetReferences(references, refType);
        }
    }
}
